joy_node:
    ros__parameters:
        device_id: 0
        device_name: "''"
        deadzone: 0.5
        autorepeat_rate: 20.0
        sticky_buttons: false
        coalesce_interval_ms: 1

teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.7
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: 0.4

    enable_button: 8  # L2 shoulder button
    enable_turbo_button: 10  # L1 shoulder button

